# build environment
FROM node:14-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json setup.js yarn.lock tsconfig.json tsconfig.paths.json tsconfig.qa.json svgTransform.js setup.js jest.unit.config.js craco.config.js config-overrides.js .env ./
RUN yarn install --frozen-lockfile --silent
COPY . ./
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
