export enum PrDashboardTestIds {
    logo = 'logo',
    title = 'title',
    addTab = 'add-tab',
    addText = 'add-text',
    addBtn = 'add-btn',
    addMetric = 'add-metric',
    addMetricOption = 'add-metric-option',
    dateFrom = 'date-from',
    dateTo = 'date-to',
    tab = 'tab',
    tabActive = 'tab-active',
    tabNumeric = 'tab-',
    tabClose = 'tab-close',
    tabCloseNumeric = 'tab-close-',
    chartSelected = 'chart-selected',
    chartTime = 'chart-time',
    chartLoading = 'chart-time-loading',
    chartError = 'chart-error',
    chartTimeKpi = 'chart-time-kpi',
    chartGroups = 'chart-groups',
    chartGroupsLoading = 'chart-groups-loading',
    chartGroupsKpi = 'chart-groups-kpi',
    sectionDates = 'section-dates',
    sectionTabs = 'section-tabs',
    sectionAdd = 'section-add',
    sectionChart = 'section-chart'
}
