name: React CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: flasher2085/react-test
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
